# Generated by Django 5.2 on 2025-05-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0003_alter_knowledgebase_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="knowledgebase",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
