# Generated by Django 5.2 on 2025-04-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_thinking_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="attachments",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
