# Generated by Django 5.2 on 2025-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="llmmodel",
            options={
                "ordering": ["order", "provider", "name"],
                "verbose_name": "LLM模型",
                "verbose_name_plural": "LLM模型",
            },
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="order",
            field=models.IntegerField(
                default=0, help_text="排序顺序，数字越小排越靠前"
            ),
        ),
    ]
