# Generated by Django 5.2 on 2025-05-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_manager", "0002_alter_llmmodel_options_llmmodel_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemprompt",
            name="is_global",
            field=models.BooleanField(default=False, verbose_name="全局提示词"),
        ),
    ]
